name 'Analytical Labs-analyticallabs'
version '1.0'

author 'Tom Barber'
license ''
project_page 'https://github.com/OSBI/puppet-analyticallabs'
source 'git@github.com:OSBI/puppet-analyticallabs.git'
summary 'Analytical Lab Controller Module'
description 'Stuff that controls the Analytical Labs servers'
dependency 'Analytical Labs/artifactory', '==1.0'
dependency 'Analytical Labs/mysql', '==1.0'
dependency 'Analytical Labs/apache', '==1.0'
dependency 'Analytical Labs/saiku', '==1.0'
dependency 'Analytical Labs/motd', '==1.0'
dependency 'Analytical Labs/xen', '==1.0'
dependency 'Analytical Labs/zabbix', '==1.0'
dependency 'Analytical Labs/nodejs', '==1.0'
